// Vue page source restored from the packaged app; template, IPC and asset paths are kept unchanged.
// Page path: src/windows/tool/floatStyle/index.js
(() => {
  var t = {};
  let e = [
    "😀",
    "😁",
    "😃",
    "😄",
    "😅",
    "😆",
    "😉",
    "😊",
    "😋",
    "😎",
    "😍",
    "😘",
    "😗",
    "😙",
    "😚",
    "☺",
    "😇",
    "😐",
    "😑",
    "😶",
    "😏",
    "😣",
    "😥",
    "😮",
    "😯",
    "😪",
    "😫",
    "😴",
    "😌",
    "😛",
    "😜",
    "😝",
    "😒",
    "😓",
    "😔",
    "😕",
    "😲",
    "😷",
    "😖",
    "😞",
    "😟",
    "😤",
    "😢",
    "😭",
    "😦",
    "😧",
    "😨",
    "😬",
    "😰",
    "😱",
    "😳",
    "😵",
    "😡",
    "😠",
    "👦",
    "👧",
    "👨",
    "👩",
    "👴",
    "👵",
    "👶",
    "👱",
    "👮",
    "👲",
    "👳",
    "👷",
    "👸",
    "💂",
    "🎅",
    "👰",
    "👼",
    "💆",
    "💇",
    "🙍",
    "🙎",
    "🙅",
    "🙆",
    "💁",
    "🙋",
    "🙇",
    "🙌",
    "🙏",
    "👤",
    "👥",
    "🚶",
    "🏃",
    "👯",
    "💃",
    "👫",
    "👬",
    "👭",
    "💏",
    "💑",
    "👪",
    "💪",
    "👈",
    "👉",
    "☝",
    "👆",
    "👇",
    "✌",
    "✋",
    "👌",
    "👍",
    "👎",
    "✊",
    "👊",
    "👋",
    "👏",
    "👐",
    "✍",
    "👣",
    "👀",
    "👂",
    "👃",
    "👅",
    "👄",
    "💋",
    "👓",
    "👔",
    "👕",
    "👖",
    "👗",
    "👘",
    "👙",
    "👛",
    "👜",
    "👝",
    "🎒",
    "💼",
    "👞",
    "👟",
    "👠",
    "👡",
    "👢",
    "👑",
    "👒",
    "🎩",
    "🎓",
    "💄",
    "💅",
    "💍",
    "🌂",
    "📶",
    "📳",
    "📴",
    "♻",
    "🏧",
    "🚮",
    "🚰",
    "♿",
    "🚹",
    "🚺",
    "🚻",
    "🚼",
    "🚾",
    "⚠",
    "🚸",
    "⛔",
    "🚫",
    "🚳",
    "🚭",
    "🚯",
    "🚱",
    "🚷",
    "🔞",
    "💈",
    "🙈",
    "🙉",
    "🙊",
    "🐵",
    "🐒",
    "🐶",
    "🐕",
    "🐩",
    "🐺",
    "🐱",
    "😺",
    "😸",
    "😹",
    "😻",
    "😼",
    "😽",
    "🙀",
    "😿",
    "😾",
    "🐈",
    "🐯",
    "🐅",
    "🐆",
    "🐴",
    "🐎",
    "🐮",
    "🐂",
    "🐃",
    "🐄",
    "🐷",
    "🐖",
    "🐗",
    "🐽",
    "🐏",
    "🐑",
    "🐐",
    "🐪",
    "🐫",
    "🐘",
    "🐭",
    "🐁",
    "🐀",
    "🐹",
    "🐰",
    "🐇",
    "🐻",
    "🐨",
    "🐼",
    "🐾",
    "🐔",
    "🐓",
    "🐣",
    "🐤",
    "🐥",
    "🐦",
    "🐧",
    "🐸",
    "🐊",
    "🐢",
    "🐍",
    "🐲",
    "🐉",
    "🐳",
    "🐋",
    "🐬",
    "🐟",
    "🐠",
    "🐡",
    "🐙",
    "🐚",
    "🐌",
    "🐛",
    "🐜",
    "🐝",
    "🐞",
    "🦋",
    "💐",
    "🌸",
    "💮",
    "🌹",
    "🌺",
    "🌻",
    "🌼",
    "🌷",
    "🌱",
    "🌲",
    "🌳",
    "🌴",
    "🌵",
    "🌾",
    "🌿",
    "🍀",
    "🍁",
    "🍂",
    "🍃",
    "🌍",
    "🌎",
    "🌏",
    "🌐",
    "🌑",
    "🌒",
    "🌓",
    "🌔",
    "🌕",
    "🌖",
    "🌗",
    "🌘",
    "🌙",
    "🌚",
    "🌛",
    "🌜",
    "☀",
    "🌝",
    "🌞",
    "⭐",
    "🌟",
    "🌠",
    "☁",
    "⛅",
    "☔",
    "⚡",
    "❄",
    "🔥",
    "💧",
    "🌊",
    "🍅",
    "🍆",
    "🌽",
    "🍄",
    "🌰",
    "🍞",
    "🍖",
    "🍗",
    "🍔",
    "🍟",
    "🍕",
    "🍳",
    "🍲",
    "🍱",
    "🍘",
    "🍙",
    "🍚",
    "🍛",
    "🍜",
    "🍝",
    "🍠",
    "🍢",
    "🍣",
    "🍤",
    "🍥",
    "🍡",
    "🍦",
    "🍧",
    "🍨",
    "🍩",
    "🍪",
    "🎂",
    "🍰",
    "🍫",
    "🍬",
    "🍭",
    "🍮",
    "🍯",
    "🍼",
    "☕",
    "🍵",
    "🍶",
    "🍷",
    "🍸",
    "🍹",
    "🍺",
    "🍻",
    "🍴",
    "🎪",
    "🎭",
    "🎨",
    "🎰",
    "🚣",
    "🛀",
    "🎫",
    "🏆",
    "⚽",
    "⚾",
    "🏀",
    "🏈",
    "🏉",
    "🎾",
    "🎱",
    "🎳",
    "⛳",
    "🎣",
    "🎽",
    "🎿",
    "🏂",
    "🏄",
    "🏇",
    "🏊",
    "🚴",
    "🚵",
    "🎯",
    "🎮",
    "🎲",
    "🎷",
    "🎸",
    "🎺",
    "🎻",
    "🎬",
    "😈",
    "👿",
    "👹",
    "👺",
    "💀",
    "☠",
    "👻",
    "👽",
    "👾",
    "💣",
    "🌋",
    "🗻",
    "🏠",
    "🏡",
    "🏢",
    "🏣",
    "🏤",
    "🏥",
    "🏦",
    "🏨",
    "🏩",
    "🏪",
    "🏫",
    "🏬",
    "🏭",
    "🏯",
    "🏰",
    "💒",
    "🗼",
    "🗽",
    "⛪",
    "⛲",
    "🌁",
    "🌃",
    "🌆",
    "🌇",
    "🌉",
    "🌌",
    "🎠",
    "🎡",
    "🎢",
    "🚂",
    "🚃",
    "🚄",
    "🚅",
    "🚆",
    "🚇",
    "🚈",
    "🚉",
    "🚊",
    "🚝",
    "🚞",
    "🚋",
    "🚌",
    "🚍",
    "🚎",
    "🚏",
    "🚐",
    "🚑",
    "🚒",
    "🚓",
    "🚔",
    "🚕",
    "🚖",
    "🚗",
    "🚘",
    "🚚",
    "🚛",
    "🚜",
    "🚲",
    "⛽",
    "🚨",
    "🚥",
    "🚦",
    "🚧",
    "⚓",
    "⛵",
    "🚤",
    "🚢",
    "✈",
    "💺",
    "🚁",
    "🚟",
    "🚠",
    "🚡",
    "🚀",
    "🎑",
    "🗿",
    "🛂",
    "🛃",
    "🛄",
    "🛅",
    "💌",
    "💎",
    "🔪",
    "💈",
    "🚪",
    "🚽",
    "🚿",
    "🛁",
    "⌛",
    "⏳",
    "⌚",
    "⏰",
    "🎈",
    "🎉",
    "🎊",
    "🎎",
    "🎏",
    "🎐",
    "🎀",
    "🎁",
    "📯",
    "📻",
    "📱",
    "📲",
    "☎",
    "📞",
    "📟",
    "📠",
    "🔋",
    "🔌",
    "💻",
    "💽",
    "💾",
    "💿",
    "📀",
    "🎥",
    "📺",
    "📷",
    "📹",
    "📼",
    "🔍",
    "🔎",
    "🔬",
    "🔭",
    "📡",
    "💡",
    "🔦",
    "🏮",
    "📔",
    "📕",
    "📖",
    "📗",
    "📘",
    "📙",
    "📚",
    "📓",
    "📃",
    "📜",
    "📄",
    "📰",
    "📑",
    "🔖",
    "💰",
    "💴",
    "💵",
    "💶",
    "💷",
    "💸",
    "💳",
    "✉",
    "📧",
    "📨",
    "📩",
    "📤",
    "📥",
    "📦",
    "📫",
    "📪",
    "📬",
    "📭",
    "📮",
    "✏",
    "✒📝",
    "📁",
    "📂",
    "📅",
    "📆",
    "📇",
    "📈",
    "📉",
    "📊",
    "📋",
    "📌",
    "📍",
    "📎📏📐",
    "✂",
    "🔒",
    "🔓",
    "🔏",
    "🔐",
    "🔑",
    "🔨",
    "🔫",
    "🔧",
    "🔩",
    "🔗",
    "💉",
    "💊",
    "🚬",
    "🔮",
    "🚩",
    "💦",
    "💨",
    "♠",
    "♥",
    "♦",
    "♣",
    "🀄",
    "🎴",
    "🔇",
    "🔈",
    "🔉",
    "🔊",
    "📢",
    "📣",
    "💤",
    "💢",
    "💬",
    "💭",
    "♨",
    "🌀",
    "🔔",
    "🔕",
    "✡",
    "✝",
    "🔯",
    "📛",
    "🔰",
    "🔱",
    "⭕",
    "✅",
    "☑",
    "✔",
    "✖",
    "❌",
    "❎",
    "➕",
    "➖",
    "➗",
    "➰",
    "➿",
    "〽",
    "✳",
    "✴",
    "❇",
    "‼",
    "⁉",
    "❓",
    "❔",
    "❕",
    "❗",
    "©",
    "®",
    "™",
    "🎦",
    "🔅",
    "🔆",
    "💯",
    "🔠",
    "🔡",
    "🔢",
    "🔣",
    "🔤",
    "🅰",
    "🆎",
    "🅱",
    "🆑",
    "🆒",
    "🆓",
    "ℹ🆔",
    "Ⓜ",
    "🆕",
    "🆖",
    "🅾",
    "🆗",
    "🅿",
    "🆘",
    "🆙",
    "🆚",
    "🈁",
    "🈂",
    "🈷",
    "🈶",
    "🈯",
    "🉐",
    "🈹",
    "🈚",
    "🈲",
    "🉑",
    "🈸",
    "🈴",
    "🈳",
    "㊗",
    "㊙",
    "🈺",
    "🈵",
    "▪",
    "▫",
    "◻",
    "◼",
    "◽",
    "◾",
    "⬛",
    "⬜",
    "🔶",
    "🔷",
    "🔸",
    "🔹",
    "🔺",
    "🔻",
    "💠",
    "🔲",
    "🔳",
    "⚪",
    "⚫",
    "🔴",
    "🔵",
    "♈",
    "♉",
    "♊",
    "♋",
    "♌",
    "♍",
    "♎",
    "♏",
    "♐",
    "♑",
    "♒",
    "♓",
    "⛎",
    "🕛",
    "🕧",
    "🕐",
    "🕜",
    "🕑",
    "🕝",
    "🕒",
    "🕞",
    "🕓",
    "🕟",
    "🕔",
    "🕠",
    "🕕",
    "🕡",
    "🕖",
    "🕢",
    "🕗",
    "🕣",
    "🕘",
    "🕤",
    "🕙",
    "🕥",
    "🕚",
    "🕦",
    "⏱",
    "⏲",
    "🕰",
    "💘",
    "❤",
    "💓",
    "💔",
    "💕",
    "💖",
    "💗",
    "💙",
    "💚",
    "💛",
    "💜",
    "💝",
    "💞",
    "💟",
    "❣",
    "🍇",
    "🍈",
    "🍉",
    "🍊",
    "🍋",
    "🍌",
    "🍍",
    "🍎",
    "🍏",
    "🍐",
    "🍑",
    "🍒",
    "🍓",
    "⬆",
    "↗",
    "➡",
    "↘",
    "⬇",
    "↙",
    "⬅",
    "↖",
    "↕",
    "↔",
    "↩",
    "↪",
    "⤴",
    "⤵",
    "🔃",
    "🔄",
    "🔙",
    "🔚",
    "🔛",
    "🔜",
    "🔝",
    "♚",
    "♛",
    "♝",
    "♞",
    "♜",
    "♟",
    "♔",
    "♕",
    "♗",
    "♘",
    "♖",
    "◯",
  ];
  var i = (t) => {
    window.electronAPI.floatStyle_h_bus(t);
  };
  const o = {
    data: () => ({
      toSee: !0,
      much: 0,
      op: 0,
      opmou: 0,
      opline: 0,
      pointSize: 0,
      background: null,
      open: !1,
      show: !1,
      closeShowTime: null,
      starT: 1,
      starSize: 25,
      starContent: "*",
      starContentData: "",
      isPenetrate: !1,
      openInfoTip: !1,
      openChangeShow: !1,
      maxChars: 10,
      emoji: e,
      hideTipIcon: !1,
      hideIconTime: null,
      showIcon: !0,
      showControl: { kjj: !0, line: !1, normal: !0 },
      lineOption: {
        show: !1,
        border: 0,
        borderType: "solid",
        borderColor: "#fff",
        opacity: 0.1,
      },
      windowTipData: null,
      windowTipPosition: [0, 0],
    }),
    computed: {},
    watch: {
      show() {
        this.show ||
          (this.hideIconTime && clearTimeout(this.hideIconTime),
          (this.hideTipIcon = !0));
      },
    },
    created() {},
    mounted() {
      (this.hideIconTime && clearTimeout(this.hideIconTime),
        (this.hideIconTime = setTimeout(() => {
          this.hideTipIcon = !0;
        }, 1e3)),
        this.init(),
        window.electronAPI.floatStyle_m_bus((t, e) => {
          "load" == e.type && seeApp();
        }),
        window.electronAPI.floatStyle_m_changeData((t, e) => {
          if ("open" == e.type)
            return (
              (this.open = !this.open),
              (this.show = !0),
              (this.hideTipIcon = !1),
              clearTimeout(this.closeShowTime),
              void (this.closeShowTime = setTimeout(() => {
                (this.openInfoTip && this.open) || (this.show = !1);
              }, 3e3))
            );
          if ("background" == e.type && e.data) {
            for (let t in e.data) this[t] = e.data[t];
            this.background
              ? e.data?.much &&
                (this.background.getcolor(), this.background.getdos())
              : (this.background = this.initBackground());
          } else "see" == e.type && (this.toSee = !this.toSee);
        }),
        i({ event: "mounted" }));
    },
    methods: {
      rulerStyle() {
        let t = this.lineOption;
        return {
          border: t.border + "px " + t.borderType + " " + t.borderColor,
          opacity: t.show ? 0 : t.opacity,
        };
      },
      init() {
        this.createStar();
      },
      toHeat(t, e, i) {
        function o(t) {
          var i = e.createElement("div");
          ((i.className = "heart"),
            n.push({
              el: i,
              x: t.clientX - 5,
              y: t.clientY - 5,
              scale: 1,
              alpha: 1,
              color:
                "rgb(" +
                ~~(255 * Math.random()) +
                "," +
                ~~(255 * Math.random()) +
                "," +
                ~~(255 * Math.random()) +
                ")",
            }),
            e.body.appendChild(i));
        }
        var n = [];
        ((t.requestAnimationFrame =
          t.requestAnimationFrame ||
          t.webkitRequestAnimationFrame ||
          t.mozRequestAnimationFrame ||
          t.oRequestAnimationFrame ||
          t.msRequestAnimationFrame ||
          function (t) {
            setTimeout(t, 1e3 / 60);
          }),
          (function (t) {
            var i = e.createElement("style");
            i.type = "text/css";
            try {
              i.appendChild(e.createTextNode(t));
            } catch (e) {
              i.styleSheet.cssText = t;
            }
            e.getElementsByTagName("head")[0].appendChild(i);
          })(
            ".heart{width: 10px;height: 10px;position: fixed;background: #f00;transform: rotate(45deg);-webkit-transform: rotate(45deg);-moz-transform: rotate(45deg);}.heart:after,.heart:before{content: '';width: inherit;height: inherit;background: inherit;border-radius: 50%;-webkit-border-radius: 50%;-moz-border-radius: 50%;position: fixed;}.heart:after{top: -5px;}.heart:before{left: -5px;}",
          ),
          (function () {
            var e = "function" == typeof t.onclick && t.onclick;
            t.onclick = function (t) {
              (e && e(), o(t));
            };
          })(),
          (function t() {
            for (var i = 0; i < n.length; i++)
              n[i].alpha <= 0
                ? (e.body.removeChild(n[i].el), n.splice(i, 1))
                : (n[i].y--,
                  (n[i].scale += 0.004),
                  (n[i].alpha -= 0.013),
                  (n[i].el.style.cssText =
                    "left:" +
                    n[i].x +
                    "px;top:" +
                    n[i].y +
                    "px;opacity:" +
                    n[i].alpha +
                    ";transform:scale(" +
                    n[i].scale +
                    "," +
                    n[i].scale +
                    ") rotate(45deg);background:" +
                    n[i].color +
                    ";z-index:99999"));
            requestAnimationFrame(t);
          })());
      },
      createStar() {
        let t = this;
        var e = window.innerWidth,
          i = (window.innerHeight, { x: e / 2, y: e / 2 }),
          o = [];
        function n() {
          ((this.character = t.starContent),
            (this.lifeSpan = 120),
            (this.initialStyles = {
              position: "fixed",
              display: "inline-block",
              top: "0px",
              left: "0px",
              pointerEvents: "none",
              "touch-action": "none",
              "z-index": "10000000",
              fontSize: t.starSize + "px",
              "will-change": "transform",
            }),
            (this.init = function (t, e, i) {
              ((this.velocity = {
                x: (Math.random() < 0.5 ? -1 : 1) * (Math.random() / 2),
                y: 1,
              }),
                (this.position = { x: t + 10, y: e + 10 }),
                (this.initialStyles.color = i),
                (this.element = document.createElement("span")),
                (this.element.innerHTML = this.character),
                (function (t, e) {
                  for (var i in e) t.style[i] = e[i];
                })(this.element, this.initialStyles),
                this.update(),
                document
                  .querySelector(".js-cursor-container")
                  .appendChild(this.element));
            }),
            (this.update = function () {
              ((this.position.x += this.velocity.x),
                (this.position.y += this.velocity.y),
                this.lifeSpan--,
                (this.element.style.transform =
                  "translate3d(" +
                  this.position.x +
                  "px," +
                  this.position.y +
                  "px, 0) scale(" +
                  this.lifeSpan / 120 +
                  ")"));
            }),
            (this.die = function () {
              this.element.parentNode.removeChild(this.element);
            }));
        }
        "ontouchstart" in window ||
          navigator.msMaxTouchPoints ||
          (document.addEventListener("mousemove", function (e) {
            var a, s, r, h;
            ((i.x = e.clientX),
              (i.y = e.clientY),
              (a = i.x),
              (s = i.y),
              (r = `rgb(${Math.trunc(256 * Math.random())},${Math.trunc(256 * Math.random())},${Math.trunc(256 * Math.random())})`),
              (h = new n()).init(a, s, r),
              o.push(h),
              t.mouseTo(e));
          }),
          window.addEventListener("resize", function (t) {
            ((e = window.innerWidth), window.innerHeight);
          }),
          (function t() {
            (requestAnimationFrame(t),
              (function () {
                for (var t = 0; t < o.length; t++) o[t].update();
                for (t = o.length - 1; t >= 0; t--)
                  o[t].lifeSpan < 0 && (o[t].die(), o.splice(t, 1));
              })());
          })());
      },
      initBackground() {
        let t = this;
        var e,
          i,
          o = document.getElementById("frist"),
          n = [],
          a = () => {
            ((e = document.documentElement.clientWidth),
              (i = document.documentElement.clientHeight));
          };
        function s() {
          n = [];
          for (var e = 0; e < t.much; e++) {
            var i = Math.random() * (o.width - 2 * t.pointSize) + t.pointSize,
              a = Math.random() * (o.height - 2 * t.pointSize) + t.pointSize,
              s = (2 * Math.random() - 1) / 1.5,
              r = (2 * Math.random() - 1) / 1.5;
            n.splice(e, 1, { x: i, y: a, xa: s, ya: r });
          }
        }
        (a(),
          (o.width = e - 8),
          (o.height = i - 8),
          s(),
          (window.onresize = () => {
            (a(), (o.width = e - 8), (o.height = i - 8), s());
          }));
        var r = o.getContext("2d"),
          h = [],
          l = () => {
            for (var e = 0; e < t.much + 3; e++) {
              var i = parseInt(256 * Math.random());
              h.splice(e, 1, i);
            }
          };
        l();
        var c = { x: -1e3, y: -1e3, max: 2e4 };
        o.onmousemove = function (t) {
          ((t = t || window.event), (c.x = t.clientX), (c.y = t.clientY));
        };
        var d = () => {
          r.clearRect(0, 0, o.width, o.height);
          for (var e = 0; e < n.length; e++) {
            ((n[e].xa *= n[e].x > o.width - t.pointSize ? -1 : 1),
              (n[e].ya *= n[e].y > o.height - t.pointSize ? -1 : 1),
              (n[e].xa *= n[e].x < t.pointSize ? -1 : 1),
              (n[e].ya *= n[e].y < t.pointSize ? -1 : 1),
              (n[e].x += n[e].xa),
              (n[e].y += n[e].ya));
            var i = h[e],
              a = h[e + 1],
              s = h[e + 2];
            ((r.fillStyle = "rgba(" + i + "," + a + "," + s + "," + t.op + ")"),
              r.beginPath(),
              r.arc(n[e].x, n[e].y, t.pointSize, 0, 2 * Math.PI, !0),
              r.closePath(),
              r.fill());
            for (var l = [c].concat(n), p = 0; p < l.length; p++) {
              var m = l[p];
              if (n[e] !== m && null !== m.x && null !== m.y) {
                var u,
                  w = n[e].x - m.x,
                  y = n[e].y - m.y,
                  f = w * w + y * y;
                f < m.max &&
                  (m === c &&
                    f > m.max / 2 &&
                    ((n[e].x -= 0.01 * w), (n[e].y -= 0.01 * y)),
                  (u = (m.max - f) / m.max),
                  r.beginPath(),
                  (r.lineWidth = u / 2),
                  (r.strokeStyle =
                    "rgba(" + i + "," + a + "," + s + "," + t.opmou + ")"),
                  r.moveTo(n[e].x, n[e].y),
                  r.lineTo(m.x, m.y),
                  r.stroke());
                var T = n[e].x,
                  g = n[e].y,
                  x = m.x,
                  S = m.y,
                  v = x - T,
                  b = S - g;
                Math.sqrt(+Math.pow(v, 2) + +Math.pow(b, 2)) < 200 &&
                  (r.beginPath(),
                  (r.lineWidth = 0.1),
                  (r.strokeStyle =
                    "rgba(" + i + "," + a + "," + s + "," + t.opline + ")"),
                  r.moveTo(T, g),
                  r.lineTo(x, S),
                  r.stroke());
              }
            }
          }
          requestAnimationFrame(d);
        };
        return (d(), { getdos: s, getcolor: l });
      },
      openInfoDataSee(t) {
        ((this.hideTipIcon = !1),
          t
            ? ((this.openInfoTip = !this.openInfoTip),
              this.openInfoTip
                ? (clearTimeout(this.closeShowTime), (this.show = !0))
                : (clearTimeout(this.closeShowTime),
                  (this.closeShowTime = setTimeout(() => {
                    ((this.show = !1),
                      (this.isPenetrate = !1),
                      window.electronAPI.floatStyle_ToMain_eventMouse({
                        canDoType: this.isPenetrate,
                      }));
                  }, 1e3))))
            : window.electronAPI.floatStyle_h_openKJ({ open: !0 }));
      },
      mouseTo(t) {
        (t.target.hasAttribute("iconTip")
          ? (this.windowTipData = {
              type: "icon",
              icon: t.target.getAttribute("iconTip"),
            })
          : (this.windowTipData = null),
          (this.windowTipPosition = [t.clientX, t.clientY]));
        let e = t.target.hasAttribute("candoMust"),
          i = !(!e || !this.showIcon) || this.show;
        ((this.show = i), i || return8);
        let o = t.target.hasAttribute("cando") || e;
        (o &&
          (clearTimeout(this.closeShowTime),
          (this.closeShowTime = setTimeout(() => {
            (this.openInfoTip && this.open) ||
              ((this.show = !1),
              (this.isPenetrate = !1),
              window.electronAPI.floatStyle_ToMain_eventMouse({
                canDoType: this.isPenetrate,
              }));
          }, 1e3))),
          this.isPenetrate != o &&
            ((this.isPenetrate = o),
            window.electronAPI.floatStyle_ToMain_eventMouse({
              canDoType: this.isPenetrate,
            })));
      },
      openChange(t) {
        ((this.openChangeShow = !this.openChangeShow),
          (this.starContentData = t));
      },
      submit() {
        this.starContentData &&
          this.starContent != this.starContentData &&
          ((this.starContent = this.starContentData),
          (this.openChangeShow = !1),
          window.electronAPI.floatStyle_h_save(
            JSON.stringify({ starContent: this.starContent }),
          ));
      },
      limitInput() {
        this.starContentData.length > this.maxChars &&
          (this.starContentData = this.starContentData.slice(0, this.maxChars));
      },
      chooseIcon(t) {
        this.starContentData += t;
      },
      openCortrol(t) {
        ((this.showControl[t] = !this.showControl[t]),
          window.electronAPI.floatStyle_h_save(
            JSON.stringify({ showControl: this.showControl }),
          ));
      },
      closeWindow() {
        i({ event: "close" });
      },
    },
  };
  Vue.createApp(o).mount("#app");
  var n = window;
  for (var a in t) n[a] = t[a];
  t.__esModule && Object.defineProperty(n, "__esModule", { value: !0 });
})();
